package com.mynamesraph.ensemble.registry

import com.mojang.blaze3d.platform.InputConstants
import com.mynamesraph.ensemble.Constants
import com.mynamesraph.ensemble.EnsembleCommon
import net.minecraft.client.KeyMapping
import org.lwjgl.glfw.GLFW

const val keyBase = "key.${Constants.MOD_ID}"

enum class EnsembleKeyMappings(val keyMapping: KeyMapping) {
    OCTAVE_MODIFIER(
        KeyMapping(
            "$keyBase.a.octave_modifier",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_RIGHT_ALT,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    DO(
        KeyMapping(
            "$keyBase.b.do",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_F,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    RE(
    KeyMapping(
        "$keyBase.c.re",
        InputConstants.Type.KEYSYM,
        GLFW.GLFW_KEY_G,
        EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    MI(
        KeyMapping(
            "$keyBase.d.mi",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_H,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    FA(
        KeyMapping(
            "$keyBase.e.fa",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_J,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    SOL(
        KeyMapping(
            "$keyBase.f.sol",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_K,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    LA(
        KeyMapping(
            "$keyBase.g.la",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_L,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    SI(
        KeyMapping(
            "$keyBase.h.si",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_SEMICOLON,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    DO_HIGH(
        KeyMapping(
            "$keyBase.i.do_high",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_R,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    RE_HIGH(
        KeyMapping(
            "$keyBase.j.re_high",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_T,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    MI_HIGH(
        KeyMapping(
            "$keyBase.k.mi_high",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_Y,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    FA_HIGH(
        KeyMapping(
            "$keyBase.l.fa_high",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_U,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    SOL_HIGH(
        KeyMapping(
            "$keyBase.m.sol_high",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_I,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    LA_HIGH(
        KeyMapping(
            "$keyBase.n.la_high",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_O,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    SI_HIGH(
        KeyMapping(
            "$keyBase.o.si_high",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_P,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    ),
    DO_HIGHER(
        KeyMapping(
            "$keyBase.p.do_higher",
            InputConstants.Type.KEYSYM,
            GLFW.GLFW_KEY_LEFT_BRACKET,
            EnsembleCommon.ENSEMBLE_KEYS_CATEGORY
        )
    )
}