package com.mynamesraph.ensemble

import com.mynamesraph.ensemble.registry.EnsembleKeyMappings

enum class Notes(val keyMapping: EnsembleKeyMappings, val pitchValue: Int,val simpleNoteName : String) {
    DO(
        EnsembleKeyMappings.DO,
        0,
        "do"
    ),
    RE(
        EnsembleKeyMappings.RE,
        1,
        "re"
    ),
    MI(
        EnsembleKeyMappings.MI,
        2,
        "mi"
    ),
    FA(
        EnsembleKeyMappings.FA,
        3,
        "fa"
    ),
    SOL(
        EnsembleKeyMappings.SOL,
        4,
        "sol"
    ),
    LA(
        EnsembleKeyMappings.LA,
        5,
        "la"
    ),
    SI(
        EnsembleKeyMappings.SI,
        6,
        "si"
    ),
    DO_HIGH(
        EnsembleKeyMappings.DO_HIGH,
        7,
        "do"
    ),
    RE_HIGH(
        EnsembleKeyMappings.RE_HIGH,
        8,
        "re"
    ),
    MI_HIGH(
        EnsembleKeyMappings.MI_HIGH,
        9,
        "mi"
    ),
    FA_HIGH(
        EnsembleKeyMappings.FA_HIGH,
        10,
        "fa"
    ),
    SOL_HIGH(
        EnsembleKeyMappings.SOL_HIGH,
        11,
        "sol"
    ),
    LA_HIGH(
        EnsembleKeyMappings.LA_HIGH,
        12,
        "la"
    ),
    SI_HIGH(
        EnsembleKeyMappings.SI_HIGH,
        13,
        "si"
    ),
    DO_HIGHER(
        EnsembleKeyMappings.DO_HIGHER,
        14,
        "do"
    )

}